### ISSUE TITLE
Moving vehicle while in vehicle

### ISSUE THREAD

**Issue by Zaddion** [roboderpy/dsit#3]
You can make your vehicle or WAC aircraft fly with your physgun if you have weapons in seat enabled.

**Comment by roboderpy** [comment]
I just can't make DSit prevent move of constrained props, but i can make a cvar to disable physgun and gravgun in seats

**Comment by roboderpy** [comment]
If you need sometrhing else, post a comment. If not so, click "Close issue" near comment button
